### ISSUE TITLE
Track imports and load modules

### ISSUE THREAD

**Issue by haneenmahd** [bundlo/bundlo#12]
Need a important feature to track imports and load modules into the output file.

**Comment by haneenmahd** [comment]
Need to load it and before we replace it 
https://github.com/bundlo/bundlo/blob/d417efefea6be0ab328228688ff5b893f5d65543/lib/utils/readData.js#L91

**Comment by haneenmahd** [comment]
https://github.com/bundlo/bundlo/blob/a9222d3b41531d50351f091dcacfa87a3a9ee131/lib/modules/readImports.js#L5

Added the functionality to readData from modules

**Comment by haneenmahd** [comment]
### Do have an error sometimes
 While finding the path from another file we do get an error❌

- [ ] fix the error
- [ ] load multiple modules

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './config/configure.js'
Require stack:
- D:\Code\JavaScript\@bundlo\bundlo\lib\dependency\Dependency.js
- D:\Code\JavaScript\@bundlo\bundlo\lib\utils\readData.js
- D:\Code\JavaScript\@bundlo\bundlo\lib\test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at D:\Code\JavaScript\@bundlo\bundlo\lib\dependency\Dependency.js:44:41
    at Array.map (<anonymous>)
    at Dependency.deepLoading (D:\Code\JavaScript\@bundlo\bundlo\lib\dependency\Dependency.js:40:17)
    at getFilesData (D:\Code\JavaScript\@bundlo\bundlo\lib\utils\readData.js:26:30)
    at Object.<anonymous> (D:\Code\JavaScript\@bundlo\bundlo\lib\test.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Code\\JavaScript\\@bundlo\\bundlo\\lib\\dependency\\Dependency.js',
    'D:\\Code\\JavaScript\\@bundlo\\bundlo\\lib\\utils\\readData.js',
    'D:\\Code\\JavaScript\\@bundlo\\bundlo\\lib\\test.js'
  ]
}
```

https://github.com/bundlo/bundlo/blob/977bdaa00e2bad6e24c55dcfff61ee65c739fb25/lib/dependency/Dependency.js#L40-L46
